# coding: utf-8

'''
This file is to evaluate labelling results generated by models.
Developed by CVEO Team.

usage: evaluate.py [-h] -m model_name -d dataset_name -n result_name --subset
                   {train,val,test} [--cpus CPUS] [-s path] [-c cm]

Evaluate the generated labelling results.

optional arguments:
  -h, --help            show this help message and exit
  -m model_name, --model-name model_name
                        name of the trained model
  -d dataset_name, --dataset dataset_name
                        name of the dataset
  -n result_name, --name result_name
                        name of the generated labelling result
  --subset {train,val,test}
                        evaluate on validation data or test data
  --cpus CPUS           the number of cpus for multiprocessing
  -s path, --save-result-to-file path
                        save the assessment result to a file
  -c cm, --save-confusion-matrix-to-file cm
                        save the confusion matrix to a file
'''

from __future__ import print_function
from pathlib import Path
import os
import json
from multiprocessing import Pool
import argparse
import numpy as np
from tqdm import tqdm
# from osgeo import gdal, gdal_array
# from gdalconst import GA_ReadOnly
# from osgeo.gdalconst import GA_ReadOnly
import cv2



def compute_cm_png(params):  # multi cls.
    pred_path, gt_path, category_count = params
    buffer_size = 512

    cm = np.zeros([category_count, category_count], 'int64')

    pred_arr = cv2.imread(pred_path, 0).astype(np.uint8)
    gt_arr =  cv2.imread(gt_path, 0).astype(np.uint8)
    assert pred_arr.shape == gt_arr.shape

    height, width = pred_arr.shape[:]
    for pred, ref in zip(np.nditer(pred_arr), np.nditer(gt_arr)):
        cm[int(ref)][int(pred)] += 1
    
    return height * width, cm


def accuracy_assessment(pred_paths, gt_paths, category_count, cpus=8):
    '''
    accuracy assessment
    '''
    total = 0
    # initialize confusion matrix
    cm = np.zeros([category_count, category_count], 'int64')

 
    params = [(pred_path, gt_path, category_count) for (pred_path, gt_path) in zip(pred_paths, gt_paths)]
    print(len(params))

    with Pool(cpus) as p:
        for pixels, current_cm in list(tqdm(p.imap_unordered(compute_cm_png, params), total=len(params))):
            total += pixels
            cm += current_cm

    bcd_cm = np.zeros([2,2], 'int64')
    # print(cm[0][0], np.sum(cm[1:][0]), np.sum(cm[0][1:]), np.sum(cm[1:][1:]))
    bcd_cm[0,0] = cm[0][0]
    bcd_cm[1,0] = np.sum(cm[1:,0])
    bcd_cm[0,1] = np.sum(cm[0,1:])
    bcd_cm[1,1] = np.sum(cm[1:,1:])

    print(bcd_cm)
    print(cm)

    '''
      BCD:
    '''
    # oa (two cls)
    bcd_correct = np.sum(np.trace(bcd_cm))
    bcd_overall_accuracy = float(bcd_correct) / total
    
    # F1  (two cls)
    if (float(bcd_cm[0,1]) + float(bcd_cm[1,1])) != 0:
        P = float(bcd_cm[1,1]) / (float(bcd_cm[0,1]) + float(bcd_cm[1,1]))
    else:
        P = 0
    if (float(bcd_cm[1,0]) + float(bcd_cm[1,1])) != 0:
        R = float(bcd_cm[1,1]) / (float(bcd_cm[1,0]) + float(bcd_cm[1,1]))
    else:
        R = 0
    if ( P + R ) != 0:
        f1score = ( 2 * P * R) / ( P + R )
    else: 
        f1score = 0
    # f1-unchange
    if (float(cm[0,1]) + float(cm[0,0])) != 0:
        P_un = float(cm[0,0]) / (float(cm[0,1]) + float(cm[0,0]))
    else:
        P_un = 0
    if (float(cm[1,0]) + float(cm[0,0])) != 0:
        R_un = float(cm[0,0]) / (float(cm[1,0]) + float(cm[0,0]))
    else:
        R_un = 0
    if ( P_un + R_un ) != 0:
        f1score_un = ( 2 * P_un * R_un) / ( P_un + R_un )
    else: 
        f1score_un = 0
    f1_ave = (f1score + f1score_un) / 2.


    # iou (two cls)
    intersect = [0] * 2
    union = [0] * 2
    for i in range(2):
        for j in range(2):
            union[j] += bcd_cm[i][j]
            if i == j:
                intersect[j] += bcd_cm[i][j]
            else:
                union[i] += bcd_cm[i][j]
    mean_intersection_over_union = sum([float(i) / float(u) for (i, u) in zip(intersect, union) if u != 0]) / 2
    iou = [float(i) / float(u) for (i, u) in zip(intersect, union) if u != 0]
    iou_bcd_same, iou_bcd_hange = iou[:]

    # kappa  (two cls)
    s = 0
    for i in range(2):
        s += (bcd_cm[i, :] * bcd_cm[:, i]).sum()
    kappa_bcd = (total * bcd_correct - s) / (total * total - s)   



    '''
      SCD:
    '''
    # oa (multi cls)
    correct = np.sum(np.trace(cm))
    overall_accuracy = float(correct) / total
        
    # miou (multi cls)
    iou_1_same = float(cm[0,0]) / float(np.sum(cm[1:,0]) + np.sum(cm[0,1:]) - cm[0,0])
    iou_2_changed = float(np.sum(cm[1:,1:]))  / float(total - cm[0,0])
    miou_scd = float(iou_1_same + iou_2_changed) / 2.

    # SeKappa
    row_hash = float(np.sum(np.trace(cm)) - cm[0,0]) / float(total - cm[0,0])
    s = 0
    for i in range(category_count):
        if i == 0:
            s += (cm[i, 1:] * cm[1:, i]).sum()
            # continue
        else:
            s += (cm[i, :] * cm[:, i]).sum()
    yeta_hash = float(s) / float((total - cm[0,0]) ** 2)
    # print(row_hash)
    # print(yeta_hash)
    SeKappa = np.exp(iou_2_changed - 1) * (row_hash - yeta_hash) / (1 - yeta_hash)



    return ({
        'BCD':{
            'OA': round(bcd_overall_accuracy, 4),
            'F1': round(f1score, 4),
            # 'Kappa': round(kappa_bcd, 4),
            # 'IoU_BCD_same': round(iou_bcd_same, 4),
            'IoU': round(iou_bcd_hange, 4),
            'Prec': round(P,4),
            'Reca': round(R,4)
        },
        'SCD':{
            # 'OA': round(overall_accuracy, 4),
            # 'IoU_SCD_same': round(iou_1_same, 4),
            # 'IoU_SCD_change': round(iou_2_changed, 4),
            'mIoU_BCD': round(mean_intersection_over_union, 4),
            'SeK': round(SeKappa, 4),
        },
    }, cm)


def run():
    
    # second
    gt_dir_list = [
        "D:\\xltan\\dataset\\ChangeDetection\\second_dataset\\SECOND_total_test\\test_tinyset_200\\label1",
        "D:\\xltan\\dataset\\ChangeDetection\\second_dataset\\SECOND_total_test\\test_tinyset_200\\label2"
    ]
    dataset_name = 'second200'
    

    
    exp_name  = '101_clearclip_8text' # 
    exp_dir_list = [
        os.path.join('exp', dataset_name, exp_name, 'scd1'), # scd1_m3thres1,   scd1_m3thres2,  scd1
        os.path.join('exp', dataset_name, exp_name, 'scd2') # scd2_m3thres1,    scd2_m3thres2,  scd2
    ]



    pred_list, gt_list = [], []

    for gt_dir, exp_dir in zip(gt_dir_list, exp_dir_list) :
        for f in os.listdir(gt_dir):
            if str(f).endswith('.png'):
                pred_path = os.path.join(exp_dir, f)
                if os.path.exists(pred_path):
                    pred_list.append(pred_path)
                    gt_list.append(os.path.join(gt_dir, f))
    
    # print(pred_list, gt_list)

    assessment, cm = accuracy_assessment(pred_list, gt_list, category_count=7, cpus=8)

    out_assess_dir = f"eval/{dataset_name}"
    os.makedirs(out_assess_dir, exist_ok=True)
    assess_path = f"eval/{dataset_name}/{exp_name}_SCD.txt"

    with open(assess_path, 'w')as file:
        for task, eval_dict in assessment.items():
            file.write('{0}\n'.format(task))
            for metric, value in eval_dict.items():
                file.write('{0}\t{1}\n'.format(metric, value))
            file.write('\n')
        
        file.write('\n')
        for c1 in range(cm.shape[0]):
            for c2 in range(cm.shape[1]):
                file.write(f'{cm[c1][c2]}\t')
            file.write('\n')

        file.close()

    print(assessment)


if __name__ == '__main__':
    run()