# coding: utf-8

'''
This file is to evaluate labelling results generated by models.
Developed by CVEO Team.

usage: evaluate.py [-h] -m model_name -d dataset_name -n result_name --subset
                   {train,val,test} [--cpus CPUS] [-s path] [-c cm]

Evaluate the generated labelling results.

optional arguments:
  -h, --help            show this help message and exit
  -m model_name, --model-name model_name
                        name of the trained model
  -d dataset_name, --dataset dataset_name
                        name of the dataset
  -n result_name, --name result_name
                        name of the generated labelling result
  --subset {train,val,test}
                        evaluate on validation data or test data
  --cpus CPUS           the number of cpus for multiprocessing
  -s path, --save-result-to-file path
                        save the assessment result to a file
  -c cm, --save-confusion-matrix-to-file cm
                        save the confusion matrix to a file
'''

from __future__ import print_function
from pathlib import Path
import os
import json
from multiprocessing import Pool
import argparse
import numpy as np
from tqdm import tqdm
# from osgeo import gdal, gdal_array
# from gdalconst import GA_ReadOnly
# from osgeo.gdalconst import GA_ReadOnly
import cv2



def compute_cm_png(params):
    pred_path, gt_path, category_count = params
    buffer_size = 512

    cm = np.zeros([category_count, category_count], 'int64')

    # labeled_ds = gdal.Open(str(labeled_path), GA_ReadOnly)
    # reference_ds = gdal.Open(str(reference_path), GA_ReadOnly)



    # pred_arr = cv2.resize(cv2.imread(pred_path, 0).astype(np.uint8), (512,512), interpolation=cv2.INTER_LINEAR) / 255
    pred_arr = cv2.imread(pred_path, 0).astype(np.uint8) / 255
    gt_arr =  cv2.imread(gt_path, 0).astype(np.uint8) / 255
    assert pred_arr.shape == gt_arr.shape

    height, width = pred_arr.shape[:]
    for pred, ref in zip(np.nditer(pred_arr), np.nditer(gt_arr)):
        cm[int(ref)][int(pred)] += 1
    
    return height * width, cm


def accuracy_assessment(pred_paths, gt_paths, category_count, cpus=4):
    '''
    accuracy assessment
    '''
    total = 0
    # initialize confusion matrix
    cm = np.zeros([category_count, category_count], 'int64')

 
    params = [(pred_path, gt_path, category_count) for (pred_path, gt_path) in zip(pred_paths, gt_paths)]


    with Pool(cpus) as p:
        for pixels, current_cm in list(tqdm(p.imap_unordered(compute_cm_png, params), total=len(params))):
            total += pixels
            cm += current_cm

    # oa
    correct = np.sum(np.trace(cm))
    overall_accuracy = float(correct) / total

    # f1
    if (float(cm[0,1]) + float(cm[1,1])) != 0:
        P = float(cm[1,1]) / (float(cm[0,1]) + float(cm[1,1]))
    else:
        P = 0
    if (float(cm[1,0]) + float(cm[1,1])) != 0:
        R = float(cm[1,1]) / (float(cm[1,0]) + float(cm[1,1]))
    else:
        R = 0
    if ( P + R ) != 0:
        f1score = ( 2 * P * R) / ( P + R )
    else: 
        f1score = 0
    # f1-unchange
    if (float(cm[0,1]) + float(cm[0,0])) != 0:
        P_un = float(cm[0,0]) / (float(cm[0,1]) + float(cm[0,0]))
    else:
        P_un = 0
    if (float(cm[1,0]) + float(cm[0,0])) != 0:
        R_un = float(cm[0,0]) / (float(cm[1,0]) + float(cm[0,0]))
    else:
        R_un = 0
    if ( P_un + R_un ) != 0:
        f1score_un = ( 2 * P_un * R_un) / ( P_un + R_un )
    else: 
        f1score_un = 0
    f1_ave = (f1score + f1score_un) / 2.

    # miou   
    intersect = [0] * category_count
    union = [0] * category_count
    for i in range(category_count):
        for j in range(category_count):
            union[j] += cm[i][j]
            if i == j:
                intersect[j] += cm[i][j]
            else:
                union[i] += cm[i][j]
    mean_intersection_over_union = sum(
        [float(i) / float(u) for (i, u) in zip(intersect, union) if u != 0]) / category_count
    iou = [float(i) / float(u) for (i, u) in zip(intersect, union) if u != 0]
    iou_same, iou_Change = iou[:]

    # kappa
    s = 0
    for i in range(category_count):
        s += (cm[i, :] * cm[:, i]).sum()
    kappa = (total * correct - s) / (total * total - s)    

    return ({
        'OA': round(overall_accuracy, 4),
        'F1': round(f1score, 4),
        'IoU': round(iou_Change, 4),
        # 'IoU_same': round(iou_same, 4),
        # 'Kappa': round(kappa, 4),
        'F1_ave': round(f1_ave,4),
        'IoU_ave': round(mean_intersection_over_union, 4),
        'Prec': round(P,4),
        'Reca': round(R,4)
    }, cm)


def run():
    
    # dataset_name = 'cveobcd'
    # gt_dir = "D:\\xltan\\dataset\\selfown\\longwen\\cveoscd_1024_tiny200\\bcd_255\\"
    # dataset_name = 'levir1024'
    # gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\LEVIR-CD\\test\\label\\"
    # dataset_name = 'second200'
    # gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\second_dataset\\SECOND_total_test\\test_tinyset_200\\bcd\\"
    # dataset_name = 'sysu800'
    # gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\SYSU-CD\\test_pick_800\\label\\"
    # dataset_name = 'cnam200'
    # gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\CNAM-CD\\test_pick200\\label\\"

    # dataset_name = 'second1694'
    # gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\second_dataset\\SECOND_total_test\\test_all1694\\bcd\\"
    dataset_name = 'sysu4000'
    gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\SYSU-CD\\test\\label\\"
    # dataset_name = 'cnam2508'
    # gt_dir = "D:\\xltan\\dataset\\ChangeDetection\\CNAM-CD\\test_all2508\\label\\"
    

    # hpc
    # dataset_name = 'second1694'
    # gt_dir = "/home/xltan/scratch/dataset2/second/test_all1694/bcd/"
    # dataset_name = 'cnam2508'
    # gt_dir = "/home/xltan/scratch/dataset2/CNAM-CD/test_all2508/label/"


    exp_name  = 'exte_DSFA' 
    exp_dir = os.path.join('exp', dataset_name, exp_name, 'otsu')   # , 'otsu' 'cossim' '255' 'bcd' 255_m2thres 255_m3thres1 255_m3thres2

    # exp_name  = '99_gridmix_8times8_fusion2' 
    # sub_mix_name = 'feat69_sclip80_sigmoidW'
    # exp_dir = os.path.join('exp', dataset_name, exp_name, sub_mix_name, '255')   # , 'otsu' 'cossim' '255' 'bcd' 255_m2thres 255_m3thres1 255_m3thres2


    pred_list, gt_list = [], []
    for f in os.listdir(gt_dir):
        # print(f)
        if str(f).endswith('.png'):
            pred_path = os.path.join(exp_dir, f)
            if os.path.exists(pred_path):
                pred_list.append(pred_path)
                gt_list.append(os.path.join(gt_dir, f))
                # image_list.append(f)
    # print(len(pred_list), len(gt_list))

    assessment, cm = accuracy_assessment(pred_list, gt_list, category_count=2, cpus=8)

    # out_assess_dir = f"eval/{dataset_name}/{exp_name}/" # Grid
    # assess_path = f"eval/{dataset_name}/{exp_name}/{sub_mix_name}.txt" # Grid
    out_assess_dir = f"eval/{dataset_name}/" # Grid
    assess_path = f"eval/{dataset_name}/{exp_name}.txt" # Grid
    os.makedirs(out_assess_dir, exist_ok=True)
    with open(assess_path, 'w')as file:
        file.write(','.join(list(assessment.keys()))+'\n')
        file.write('\n')
        for key in assessment.keys():
            file.write('{0}\t{1}\n'.format(key, assessment[key]))
        file.write('\n')
        file.write(f'{cm[0][0]}\t{cm[0][1]}\n')
        file.write(f'{cm[1][0]}\t{cm[1][1]}\n')
        file.close()

    # if cm_path is None:
    #     cm_path = result_path/"cm.npy"
    # np.save(cm_path, cm)

    print(assessment)


if __name__ == '__main__':
    run()